name: Build and publish to public ECR

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 9 * * 1
  push:
    branches:
      - master
      - main
      - "[0-9]*"
      - "v[0-9]*"
    tags:
      - v*
      - urllib3-2.3.0
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract repo name
      shell: bash
      run: |-
        echo "repo_name=$(echo ${GITHUB_REPOSITORY} | sed 's/.*\///g' | sed 's/-docker$//')" >> $GITHUB_OUTPUT
      id: extract_repo_name
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v5
      with:
        images: public.ecr.aws/citizensadvice/${{ steps.extract_repo_name.outputs.repo_name }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha
    - name: Login to AWS Elastic Container Registry
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.PUBLIC_PUSH_ECR_AWS_KEY }}
        password: ${{ secrets.PUBLIC_PUSH_ECR_AWS_SECRET }}
      env:
        AWS_REGION: us-east-1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
